### ISSUE TITLE
Listes profils sociaux intervenants

### ISSUE THREAD

**Issue by jice-lavocat** [providenz/E1S4#1]
`<li>Benoit Laurent : Worders, TextMasters (<a href="https://www.twitter.com/BenoitLaurent" target="_blank">@BenoitLaurent</a> - <a href="https://fr.linkedin.com/in/benomad">linkedin</a>)</li>
<li>Wilfried Durand : MailJet, Tuto.com (<a href="https://www.twitter.com/wiloo" target="_blank">@wiloo</a> - <a href="https://bg.linkedin.com/in/wilfrieddurand">linkedin</a>)</li>
<li>Dimitri Pivot : Secondsouffle.org  (<a href="https://www.twitter.com/DimitriPivot" target="_blank">@DimitriPivot</a> - <a href="https://fr.linkedin.com/in/dimitri-pivot-41a9a95b/">linkedin</a>)</li>
<li>Thomas Parisot : BBC R&amp;D,  Dijiwan (<a href="https://www.twitter.com/oncletom" target="_blank">@oncletom</a>)</li>
<li>Bruno Tauziet : High-camp (<a href="https://fr.linkedin.com/in/bruno-tauziet-758b9826/">linkedin</a>)</li>
<li>Corinne Schillinger : Inseo, Alsacréations (<a href="https://www.twitter.com/schillinger" target="_blank">@schillinger</a> - <a href="https://fr.linkedin.com/in/corinne-schillinger-39710b32/en">linkedin</a>)</li>
<li>Goulven Champenois : ThinkInnovation (<a href="https://www.twitter.com/goulvench" target="_blank">@goulvench</a> - <a href="https://fr.linkedin.com/in/goulvenchampenois">linkedin</a>)</li>
<li>Bastien Jaillot : JoliCode (<a href="https://www.twitter.com/bastnic" target="_blank">@bastnic</a> - <a href="https://fr.linkedin.com/in/bastien-jaillot-3b379120/">linkedin</a>)</li>
<li>Valérie GERARD : Marinapp-SmartHarbour, Numa (<a href="https://www.twitter.com/missv4l" target="_blank">@missv4l</a> - <a href="https://fr.linkedin.com/in/vgerard/">linkedin</a>)</li>
<li>Antoine Ferrier : AdBack, DEKALEE (<a href="https://www.twitter.com/Anto1neF" target="_blank">@Anto1neF</a> - <a href="https://www.linkedin.com/in/antoine-ferrier-a066827b">linkedin</a>)</li>
<li>Matthieu Bellon : Pilot.pm (<a href="https://www.twitter.com/m_ripr" target="_blank">@m_ripr</a> - <a href="https://fr.linkedin.com/in/matthieubellon">linkedin</a>)</li>
<li>Maxime Tiberghien : Freelance, BlackTwin (<a href="https://www.twitter.com/MaximeTiberghie" target="_blank">@MaximeTiberghie</a> - <a href="https://fr.linkedin.com/in/maxime-cauchard-tiberghien-12a02153/en">linkedin</a>)</li>
<li>Brice Favre :  Ami Software (<a href="https://www.twitter.com/briceatwork" target="_blank">@briceatwork</a> - <a href="https://fr.linkedin.com/in/bricefavrev">linkedin</a>)</li>`

**Comment by jice-lavocat** [comment]
<li>Benoit Laurent : Worders, TextMasters (<a href="https://www.twitter.com/BenoitLaurent" target="_blank">@BenoitLaurent</a> - <a href="https://fr.linkedin.com/in/benomad">linkedin</a>)</li>
<li>Wilfried Durand : MailJet, Tuto.com (<a href="https://www.twitter.com/wiloo" target="_blank">@wiloo</a> - <a href="https://bg.linkedin.com/in/wilfrieddurand">linkedin</a>)</li>
<li>Dimitri Pivot : Secondsouffle.org  (<a href="https://www.twitter.com/DimitriPivot" target="_blank">@DimitriPivot</a> - <a href="https://fr.linkedin.com/in/dimitri-pivot-41a9a95b/">linkedin</a>)</li>
<li>Thomas Parisot : BBC R&amp;D,  Dijiwan (<a href="https://www.twitter.com/oncletom" target="_blank">@oncletom</a>)</li>
<li>Bruno Tauziet : High-camp (<a href="https://fr.linkedin.com/in/bruno-tauziet-758b9826/">linkedin</a>)</li>
<li>Corinne Schillinger : Inseo, Alsacréations (<a href="https://www.twitter.com/schillinger" target="_blank">@schillinger</a> - <a href="https://fr.linkedin.com/in/corinne-schillinger-39710b32/en">linkedin</a>)</li>
<li>Goulven Champenois : ThinkInnovation (<a href="https://www.twitter.com/goulvench" target="_blank">@goulvench</a> - <a href="https://fr.linkedin.com/in/goulvenchampenois">linkedin</a>)</li>
<li>Bastien Jaillot : JoliCode (<a href="https://www.twitter.com/bastnic" target="_blank">@bastnic</a> - <a href="https://fr.linkedin.com/in/bastien-jaillot-3b379120/">linkedin</a>)</li>
<li>Valérie GERARD : Marinapp-SmartHarbour, Numa (<a href="https://www.twitter.com/missv4l" target="_blank">@missv4l</a> - <a href="https://fr.linkedin.com/in/vgerard/">linkedin</a>)</li>
<li>Antoine Ferrier : AdBack, DEKALEE (<a href="https://www.twitter.com/Anto1neF" target="_blank">@Anto1neF</a> - <a href="https://www.linkedin.com/in/antoine-ferrier-a066827b">linkedin</a>)</li>
<li>Matthieu Bellon : Pilot.pm (<a href="https://www.twitter.com/m_ripr" target="_blank">@m_ripr</a> - <a href="https://fr.linkedin.com/in/matthieubellon">linkedin</a>)</li>
<li>Maxime Tiberghien : Freelance, BlackTwin (<a href="https://www.twitter.com/MaximeTiberghie" target="_blank">@MaximeTiberghie</a> - <a href="https://fr.linkedin.com/in/maxime-cauchard-tiberghien-12a02153/en">linkedin</a>)</li>
<li>Brice Favre :  Ami Software (<a href="https://www.twitter.com/briceatwork" target="_blank">@briceatwork</a> - <a href="https://fr.linkedin.com/in/bricefavrev">linkedin</a>)</li>

**Comment by providenz** [comment]
Fix dans 0b3c91600c8c9f120f7235214eb8777bb0147e84
Merci !
